when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

calculator:
    path: /calculator
    controller: App\Controller\CalculatorController::show
